import type { SkillPillar } from "./types";

export const skillPillars: SkillPillar[] = [
  {
    id: "pillar_platforms",
    slug: "enterprise-platforms",
    code: "2100",
    title: "Enterprise Platforms",
    thesis:
      "The systems of record I design against, integrate, and hold to account.",
    items: [
      "NetSuite (ERP, primary)",
      "Salesforce (CRM)",
      "Coupa",
      "Oracle EBS",
      "Avalara",
      "Vertex",
      "Stripe",
      "Workday",
      "Paycor",
      "Zip",
      "Rocketlane",
    ],
    sortOrder: 1,
  },
  {
    id: "pillar_erp_domain",
    slug: "erp-domain",
    code: "2200",
    title: "ERP Domain",
    thesis:
      "The full ledger lifecycle — order to cash to close — treated as one architecture, not separate projects.",
    items: [
      "Order to Cash (O2C)",
      "Procure to Pay (P2P)",
      "Record to Report (R2R)",
      "Revenue Recognition (ASC 606)",
      "Billing & Subscription Management",
    ],
    sortOrder: 2,
  },
  {
    id: "pillar_integration",
    slug: "integration-middleware",
    code: "2300",
    title: "Integration & Middleware",
    thesis: "Pipelines built to fail loudly, retry safely, and leave a trail.",
    items: [
      "Celigo (iPaaS)",
      "REST / SOAP APIs",
      "Middleware design",
      "AWS pipelines (S3, Transfer Family, SFTP)",
      "CI/CD",
      "Retry frameworks",
      "Observability tooling",
    ],
    sortOrder: 3,
  },
  {
    id: "pillar_engineering",
    slug: "engineering",
    code: "2400",
    title: "Engineering",
    thesis:
      "Enough depth to build what I design — and to know what shouldn't be built.",
    items: [
      "SuiteScript 1.0 / 2.x",
      "TypeScript",
      "JavaScript",
      "Python",
      "React",
      "Backbone.js",
      "SuiteCommerce Advanced",
    ],
    sortOrder: 4,
  },
  {
    id: "pillar_data",
    slug: "data-analytics",
    code: "2500",
    title: "Data & Analytics",
    thesis: "High-volume financial data made queryable, reconcilable, and fast.",
    items: [
      "SQL",
      "SuiteQL",
      "SuiteAnalytics",
      "High-volume Map/Reduce processing",
    ],
    sortOrder: 5,
  },
  {
    id: "pillar_ai",
    slug: "ai-ml",
    code: "2600",
    title: "AI & ML",
    thesis:
      "Agentic systems with guardrails first — the 20% that actually needs an LLM.",
    items: [
      "Agentic systems",
      "Model Context Protocol (MCP)",
      "LangGraph",
      "LangChain",
      "LangSmith",
      "CrewAI",
      "RAG & embeddings",
      "AI observability",
      "LLM integration POCs",
      "Python",
    ],
    sortOrder: 6,
  },
  {
    id: "pillar_governance",
    slug: "governance-quality",
    code: "2700",
    title: "Governance & Quality",
    thesis: "Controls designed in from day one, not bolted on for the audit.",
    items: [
      "SOX controls",
      "Audit processes",
      "Role-based access",
      "SIT / UAT / regression",
      "API & integration testing",
      "Data reconciliation & validation",
    ],
    sortOrder: 7,
  },
];
