import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import NachaValidator from "@/components/tools/NachaValidator";
import { getSiteProfile, getToolBySlug } from "@/lib/content";

const TITLE = "NACHA File Validator";
const DESCRIPTION =
  "Validate a NACHA (ACH) payment file before your bank rejects it. Free, runs entirely in your browser, with fix hints for NetSuite Electronic Bank Payments.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/tools/nacha-validator/" },
  openGraph: {
    type: "website",
    url: "/tools/nacha-validator/",
    title: TITLE,
    description: DESCRIPTION,
    images: [{ url: "/og.png", width: 1200, height: 630, alt: TITLE }],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og.png"],
  },
};

/**
 * FAQ content: single source for the visible section and the FAQPage
 * JSON-LD, so the two can never drift apart.
 */
const FAQ: Array<{ q: string; a: string }> = [
  {
    q: "Is my file uploaded anywhere?",
    a: "No. The validator is JavaScript running on this page. Your file is read in your browser's memory, checked there, and never sent over the network, logged, or stored. You can verify this in your browser's developer tools: the network tab stays silent while you validate.",
  },
  {
    q: "Why did my bank reject my ACH file?",
    a: "The most common causes are mechanical: control totals that do not match the entries, a routing number that fails its check digit, lines that are no longer exactly 94 characters after someone edited the file, a company ID that does not match what the bank has on file, or an invalid effective entry date. This validator catches that whole class of problem before the bank does.",
  },
  {
    q: "What does the entry hash check?",
    a: "The entry hash is a checksum built from routing numbers. You add up the first 8 digits of the routing number of every entry in a batch, keep the rightmost 10 digits of the sum, and write the result in the batch control record. The file control record carries the same calculation across all batches. Banks recompute it on receipt; if it does not match, an entry was altered, added, or dropped after the totals were written.",
  },
  {
    q: "What does this tool not check?",
    a: "Anything only your bank can know. It cannot confirm that an account exists, that funds are available, that you are inside your bank's processing window, or that your company is authorized for a given SEC code. It also does not validate every rule for less common SEC codes such as IAT. Treat a clean result as a pre-flight pass, not as compliance approval.",
  },
  {
    q: "Does it work with NetSuite Electronic Bank Payments files?",
    a: "Yes, that is the workflow it was built around. ACH files generated by NetSuite's Electronic Bank Payments SuiteApp validate like any other NACHA file, and most findings include a specific fix: which vendor record, company bank detail, or EFT template field to correct in NetSuite before regenerating the file from Payment File Administration.",
  },
];

export default async function NachaValidatorPage() {
  const [tool, profile] = await Promise.all([
    getToolBySlug("nacha-validator"),
    getSiteProfile(),
  ]);
  if (!tool) notFound();

  const pageUrl = `${profile.siteUrl}/tools/${tool.slug}/`;

  const softwareJsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: TITLE,
    description: DESCRIPTION,
    url: pageUrl,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Any (runs in the browser)",
    browserRequirements: "Requires JavaScript",
    isAccessibleForFree: true,
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    author: {
      "@type": "Person",
      name: profile.name,
      url: profile.siteUrl,
      sameAs: profile.links.map((link) => link.href),
    },
  };

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };

  return (
    <div className="mx-auto max-w-5xl px-5 pt-12 sm:px-8 sm:pt-16">
      <script
        type="application/ld+json"
        // Static JSON derived from this file's constants; no user input.
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <p className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2">
        <Link
          href="/tools/"
          className="meta-label text-stamp-deep transition-colors hover:text-ink"
        >
          Tools / {tool.code}
        </Link>
        <span className="meta-label">Status · In service</span>
      </p>

      <h1 className="font-display mt-5 text-3xl leading-tight font-semibold tracking-tight sm:text-4xl">
        NACHA file validator
      </h1>

      <p className="mt-4 max-w-[62ch] text-lg leading-relaxed text-ink-muted">
        A free NACHA file validator for ACH payment files: it checks the
        structure, routing numbers, and control totals that banks verify on
        receipt, and tells you what to fix in NetSuite when something fails.
      </p>

      <p className="mt-6 max-w-[72ch] border-l-2 border-rule-strong bg-band/50 px-4 py-3 text-[0.9375rem] leading-relaxed">
        <strong>Runs entirely in your browser. Your file never leaves your
        computer.</strong>{" "}
        This is a pre-flight check to catch common rejections, not a
        substitute for your bank's or Nacha's compliance validation.
      </p>

      <div className="mt-8">
        <NachaValidator />
      </div>

      {/* ---- editorial: context and FAQ -------------------------------- */}
      <article className="mt-16 max-w-[70ch] border-t border-rule pt-10">
        <h2 className="font-display text-2xl font-semibold tracking-tight">
          What is a NACHA file?
        </h2>
        <p className="mt-4 leading-relaxed">
          A NACHA file is the plain-text format used to send batches of ACH
          payments to a bank. Nacha, the body that governs the ACH network in
          the United States, defines it down to the character: every line is a
          record of exactly 94 characters, and every field lives at fixed
          positions inside that line.
        </p>
        <p className="mt-4 leading-relaxed">
          A file opens with a file header, then one or more batches. Each
          batch has a header, entry records that carry the individual
          payments, and a control record with totals. The file closes with a
          file control record that totals everything, padded with lines of
          9s until the line count is a multiple of ten.
        </p>
        <p className="mt-4 leading-relaxed">
          That rigidity is the point. The receiving bank does not parse your
          intent; it reads position 30 through 39 and expects an amount. One
          character out of place and the whole file can bounce.
        </p>

        <h2 className="font-display mt-10 text-2xl font-semibold tracking-tight">
          What this NACHA file validator checks
        </h2>
        <p className="mt-4 leading-relaxed">
          The checks mirror what receiving banks verify first: record
          structure and ordering, the 94-character rule, file header
          constants, service class and SEC codes, transaction codes, the ABA
          check digit on every routing number, amount formats, addenda
          consistency, and every control total: entry counts, entry hash,
          debit and credit totals, batch and block counts.
        </p>
        <p className="mt-4 leading-relaxed">
          Every finding names the line, the field, and the exact character
          positions, so you can see the problem in the raw record instead of
          guessing. Files generated by NetSuite's Electronic Bank Payments
          also get a targeted fix hint, because I have spent enough hours on
          the wrong side of a bank rejection notice to know the fix is rarely
          in the file itself.
        </p>

        <h2 className="font-display mt-10 text-2xl font-semibold tracking-tight">
          Why banks reject ACH files
        </h2>
        <p className="mt-4 leading-relaxed">
          In practice, rejections cluster around a few mechanical causes. A
          hand-edited file whose control totals no longer reconcile. A vendor
          routing number with a typo that fails its check digit. A file saved
          through an editor that trimmed the trailing spaces every record
          needs. A company ID that does not match the bank's setup. An
          effective date that is not a real banking day.
        </p>
        <p className="mt-4 leading-relaxed">
          All of these are visible in the file before you upload it. That is
          the gap this tool covers: thirty seconds of validation against the
          published format, on your own machine, before the bank's nightly
          cycle finds the problem for you.
        </p>

        <h2 className="font-display mt-10 text-2xl font-semibold tracking-tight">
          Frequently asked questions
        </h2>
        <dl className="mt-2">
          {FAQ.map((item) => (
            <div key={item.q} className="mt-6">
              <dt className="font-display text-lg font-semibold tracking-tight">
                {item.q}
              </dt>
              <dd className="mt-2 leading-relaxed">{item.a}</dd>
            </div>
          ))}
        </dl>

        <p className="mt-10 border-t border-rule pt-6 font-mono text-[0.75rem] leading-relaxed text-ink-muted">
          All sample data on this page is fictional. Routing numbers are
          fabricated to pass or fail the check digit deliberately and belong
          to no real bank.
        </p>
      </article>

      <p className="mt-12">
        <Link
          href="/tools/"
          className="font-mono text-[0.75rem] font-medium tracking-[0.14em] uppercase text-ink-muted transition-colors hover:text-stamp-deep"
        >
          ← All tools
        </Link>
      </p>
    </div>
  );
}
